### ISSUE TITLE
Create packages for glibc and iconv supported encodings

### ISSUE THREAD

**Issue by jayvdb** [roskakori/CodecMapper#10]
Like the package for ebcdic, it would be useful to provide other groupings.  The most obvious way to divide them are by world regions , but another practical way to divide them by interoperability/"other authority" , being iconv and glibc.  i.e. what extra codecs do I need to have in order for python to be able to interoperate with the latest glibc or iconv.  Rather simple helpers could be made to identify the lists of missing codecs for each.

Another set is encodings created by database vendors, and only needed by anyone directly using the databases internal APIs.

https://pypi.org/search/?q=iconv&o=-created shows there are no recently updated packages for iconv . The most recently updated is https://pypi.org/project/iconvr/ , which links to https://github.com/zh5e/iconvr by @zh5e , which is 404 .

https://bugs.python.org/issue22679 lists glibc codecs missing from Python as of 2014 - listed here:

- ARMSCII-8 - Armenian encoding
- EUC-TW - Taiwan encoding in EUC family
- GEORGIAN-PS - Georgian encoding
- KOI8-T - Tajik encoding in KOI family
- RK1048 - Kazakh variation of CP1251
- TCVN5712-1 - Vietnam encoding

Of those, only EUC-TW appears to be in https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html

No doubt, the list is longer now.  I am fairly confident that EUC_CN is now in iconv - not sure if it is in glibc.  Likewise CNS11643 , which was wontfixed at https://bugs.python.org/issue2066  Japanese legacy encodings are also stuck in review https://bugs.python.org/issue23050 .

http://www.herongyang.com/Unicode/Java-charset-Supported-Character-Encodings-in-JDK.html shows jre11 , but it doesnt appear to have many more obscure encodings, but EUC-CN and CNS-11643 and Japanese legacy are there.

https://github.com/mbr/slugger/search?q=glibc&unscoped_q=glibc is one project which uses the glibc codecs.

**Comment by jayvdb** [comment]
https://github.com/openjdk/jdk/tree/6bab0f539fba8fb441697846347597b4a0ade428/src/jdk.charsets/share/classes/sun/nio/cs/ext appears to be one set of them, and more at https://github.com/openjdk/jdk/tree/6bab0f539fba8fb441697846347597b4a0ade428/make/jdk/src/classes/build/tools/charsetmapping

**Comment by roskakori** [comment]
I tend to agree with the discussion from the Python issues where the suggested encodings were considered to be rather pointless in practice. For the rare case someone really has some text in one of these encodings they could use iconv to convert them to e.g. UTF-8 and then process it with Python. Typically you do this once for migrating legacy data.

(The EBCDIC codecs on the other hand are in actual use (well, at least some of them). Also in projects with data from mainframes, some sort of EBCDIC will be used because it's the mainframe's native encoding. These machines are typically entangled in a company's infrastructure and can't be removed easily. So you can't just do a one time migration in this case.)

As a side note, for some of the Asian encodings one would have to check if they can be mapped to and 8 bit code page. Some of them might be multi-byte, in which case CodecMapper cannot be applied easily.

If someone really needs one of these encodings, they can quite easily create it with CodecMapper and upload it to PyPI as part of their own package.

So for the time being I do not see the merit of this suggestion.
